base_url: "..."
api_key: "..."

model: "internvl3-38b"

output_prefix_name: benchmark-internvl3-runs-3-batch-5
output_dir: results
save_format: csv
stream_writing: true

runs: 3
num_concurrent_requests: 5

cases:
  - input_tokens: 2000
    output_tokens: 1000

  - input_tokens: 2000
    output_tokens: 4000
  
  - input_tokens: 2000
    output_tokens: 8000

  - input_tokens: 10000
    output_tokens: 1000

  - input_tokens: 10000
    output_tokens: 4000

  - input_tokens: 10000
    output_tokens: 8000

  - input_tokens: 20000
    output_tokens: 1000

  - input_tokens: 20000
    output_tokens: 4000
  
  - input_tokens: 20000
    output_tokens: 8000

  - input_tokens: 50000
    output_tokens: 1000

  - input_tokens: 50000
    output_tokens: 4000
