base_url: "..."
api_key: "..."

model: "xlam-8b"

output_prefix_name: benchmark-xlam-runs-3-batch-20
output_dir: results
save_format: csv
stream_writing: true

runs: 3
num_concurrent_requests: 20

cases:
  - input_tokens: 2000
    output_tokens: 1000

  - input_tokens: 2000
    output_tokens: 4000
  
  - input_tokens: 2000
    output_tokens: 8000

  - input_tokens: 10000
    output_tokens: 1000

  - input_tokens: 10000
    output_tokens: 4000

  - input_tokens: 10000
    output_tokens: 8000

  - input_tokens: 20000
    output_tokens: 1000

  - input_tokens: 20000
    output_tokens: 4000
  
  - input_tokens: 20000
    output_tokens: 8000

  - input_tokens: 25000
    output_tokens: 2000

